version: "3"

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 54320:5432
    networks:
      - dance-network
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./server/devdb/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./server/devdb/2-schema.sh:/docker-entrypoint-initdb.d/2-schema.sh
      - ./server/devdb/3-seed.sh:/docker-entrypoint-initdb.d/3-seed.sh

  api:
    container_name: server
    build: ./server/.
    ports:
      - 3000:3000
    networks:
      - dance-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev-test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dance-network

networks:
  dance-network:
    driver: bridge

volumes:
  database_data:
    driver: local
