version: "3"

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 54320:5432
    networks:
      - dance-network
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./devdb/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./devdb/2-schema.sh:/docker-entrypoint-initdb.d/2-schema.sh
      - ./devdb/3-seed.sh:/docker-entrypoint-initdb.d/3-seed.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    container_name: server
    build: .
    ports:
      - 3000:3000
    networks:
      - dance-network

networks:
  dance-network:
    driver: bridge

volumes:
  database_data:
    driver: local
