version: "3"

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./2-schema.sh:/docker-entrypoint-initdb.d/2-schema.sh

volumes:
  database_data:
    driver: local
